{
    'name': "Ooops Initial Setup",
    'summary': 'Initial Ooops module install',
    'category': "web",
    'version': "14.0.1.0.14",
    "author": "Ooops",
    "contributors": ['Giovanni Serra - GSLab.it'],
    "maintainers": ['gslabit'],
    'website': 'https://www.ooops404.com',
    'depends': [
        'base_setup',
        'base_import_async',
        'disable_odoo_online',
        'gslab_backend_theme',
        'mail',
        'mail_debrand',
        'mail_environment',
        'module_auto_update',
        'ooops_nginx_ssl_google',
        'ooops_backend_debranding',
        'ooops_mail_environment',
        'ooops_tools',
        'portal_odoo_debranding',
        'queue_job_context',
        'remove_odoo_enterprise',
        'server_environment_ir_config_parameter',
        'web_environment_ribbon',
        'web_advanced_search',
        'default_multi_user',
    ],
    'data': ['data/default_data.xml', 'views/module_views.xml'],
    'license': 'LGPL-3',
    'installable': True,
    'post_init_hook': 'post_init_hook',
}
